### ISSUE TITLE
env: lua5.3 no such file or directory

### ISSUE THREAD

**Issue by mitchweaver** [kiedtl/cursed#1]
On OpenBSD I check and I do have `lua53` instead of `lua5.3`. I also don't have just `lua`.

Making this more out of curiosity out of what the "proper" way to invoke lua is?

![nolua](https://wvr.sh/u/8SPK.png)

One idea is to make a shell wrapper like so, and then invoke it in the makefile with `"PATH=.:$PATH"`

```
#!/bin/sh
for lua in lua5.3 lua53 lua ; do
    if command -v $lua >/dev/null ; then
        exec $lua -- "$@"
    fi
done
```

but that's most likely not how its supposed to be done ¯\\_(ツ)_/¯

**Comment by kiedtl** [comment]
I'm not sure if the scripts are compatible with Lua 5.2 and 5.1. That was my main concern with using `lua5.3` instead of just `lua` in the shebang. (The scripts *should* be compatible, I don't think I used any 5.3-only features... *ominous music*)
